name: build-test
on: [pull_request]

jobs:
  build-test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: ubuntu:focal
            ros_distribution: foxy
          - docker_image: ubuntu:bionic
            ros_distribution: dashing
    container:
      image: ${{ matrix.docker_image }}
      options: -v /tmp/.X11-unix:/tmp/.X11-unix:rw -e DISPLAY
    steps:
      # - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.1.2
      - uses: ros-tooling/action-ros-ci@0.1.1
        with:
          package-name: xacro_live
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
