name: build-test
on: [pull_request]

jobs:
  build-test:
    name: build and test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - docker_image: ubuntu:focal
            ros_distribution: foxy
          - docker_image: ubuntu:bionic
            ros_distribution: dashing
    container:
      image: ${{ matrix.docker_image }}
      env:
        DISPLAY: :99
    steps:
      - run: apt-get update -y && apt-get install --no-install-recommends -y xvfb
      - run: Xvfb :99 &
      - uses: ros-tooling/setup-ros@0.1.2
      - uses: ros-tooling/action-ros-ci@0.1.1
        with:
          package-name: xacro_live
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: ""
