name: Ament Lint

on: [pull_request]

jobs:
  ament_lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [xmllint, flake8, copyright, pep257]
    steps:
      - uses: actions/checkout@v2
      - uses: ros-tooling/setup-ros@0.0.25
      - uses: ros-tooling/action-ros-lint@0.1.0
        with:
          linter: ${{ matrix.linter }}
          package-name: xacro_live
